import {
  // Award,
  Disc,
  DollarSign,
  // File,
  Gift,
  HardDrive,
  HelpCircle,
  Home,
  List,
  Package,
  Paperclip,
  Bell,
  Mail,
  Plus,
  Star,
  Truck,
  // User,
  Wind,
} from 'react-feather';

import {
  // FaUserAlt,
  FaStoreAlt,
  // FaOutdent,
  // FaFirstOrder,
  FaStore,
  FaArchive,
  // FaTags,
  // FaGifts,
  FaShippingFast,
  FaImages,
  FaUsers,
} from 'react-icons/fa';

import paths from 'route/paths';
export const ADMINMENUITEMS = [
  {
    menutitle: 'General',
    menucontent: 'Dashboards,Widgets',
    Items: [
      {
        title: 'Dashboard',
        icon: Home,
        type: 'link',
        active: true,
        path: '/dashboard',
      },
      {
        title: 'Shipping',
        icon: FaShippingFast,
        type: 'sub',
        active: false,
        children: [
          {
            title: 'Provinces',
            icon: HardDrive,
            type: 'link',
            active: false,
            path: paths.provinces,
          },
          {
            title: 'Districts',
            icon: Plus,
            type: 'link',
            active: false,
            path: paths.district,
          },
          {
            title: 'Municipality',
            icon: Plus,
            type: 'link',
            active: false,
            path: paths.municipality,
          },
          {
            title: 'Area',
            icon: Plus,
            type: 'link',
            active: false,
            path: paths.areas,
          },
        ],
      },
      {
        title: 'Product Library',
        icon: FaArchive,
        type: 'sub',
        active: false,

        children: [
          {
            title: 'Add Product',
            icon: HardDrive,
            type: 'link',
            active: false,
            path: '/dashboard/addProduct',
          },
          {
            title: 'All Product',
            icon: Plus,
            type: 'link',
            active: false,
            path: '/dashboard/viewProducts',
          },
        ],
      },
      // {
      //   title: 'Profile',
      //   icon: User,
      //   type: 'link',
      //   active: false,
      //   path: '/dashboard/userprofile',
      // },
      // {
      //   title: 'Dynamic Forms',
      //   icon: File,
      //   type: 'sub',
      //   active: false,
      //   path: '#',
      //   children: [
      //     {
      //       title: 'Product Form',
      //       type: 'link',
      //       active: false,
      //       path: '#',
      //       children: [
      //         {
      //           title: 'Add Form Group',
      //           icon: Plus,
      //           type: 'link',
      //           active: false,
      //           path: '/dashboard/form-group/create',
      //         },
      //         {
      //           title: 'Edit Form Group',
      //           icon: Plus,
      //           type: 'link',
      //           active: false,
      //           path: '/dashboard/form-group/edit',
      //         },
      //       ],
      //     },
      //     {
      //       title: 'Vendor Documents',
      //       icon: Home,
      //       type: 'link',
      //       active: true,
      //       path: '#',
      //       children: [
      //         {
      //           title: 'Add a new form',
      //           icon: Home,
      //           type: 'link',
      //           active: true,
      //           path: '/dashboard/vendor-document',
      //         },
      //       ],
      //     },
      //   ],
      // },
      {
        title: 'Category',
        icon: List,
        type: 'sub',
        active: false,
        path: '/dashboard/categories',
        children: [
          {
            title: 'All Category',
            icon: HardDrive,
            type: 'link',
            active: false,
            path: '/dashboard/categories',
          },
          {
            title: 'Add Category',
            icon: Plus,
            type: 'link',
            active: false,
            path: '/dashboard/category/create',
          },
        ],
      },
      {
        title: 'Brands',
        icon: Disc,
        type: 'sub',
        active: false,
        path: paths.Brands,
        children: [
          {
            title: 'All Brands',
            icon: HardDrive,
            type: 'link',
            active: false,
            path: paths.Brands,
          },
          {
            title: 'Add Brands',
            icon: Plus,
            type: 'link',
            active: false,
            path: paths.createBrand,
          },
        ],
      },
      {
        title: 'Colors',
        icon: Wind,
        type: 'sub',
        active: false,
        path: '/dashboard/colors',
        children: [
          {
            title: 'All Colors',
            icon: HardDrive,
            type: 'link',
            active: false,
            path: '/dashboard/colors',
          },
          {
            title: 'Add Colors',
            icon: Plus,
            type: 'link',
            active: false,
            path: '/dashboard/color/create',
          },
        ],
      },
      // !TODO: NO IMPLEMENTATION
      // {
      //   title: 'Variants',
      //   icon: Package,
      //   type: 'sub',
      //   active: false,
      //   path: '/dashboard/variants',
      //   children: [
      //     {
      //       title: 'All Variants',
      //       icon: HardDrive,
      //       type: 'link',
      //       active: false,
      //       path: '/dashboard/variants',
      //     },
      //     {
      //       title: 'Add Variants',
      //       icon: Plus,
      //       type: 'link',
      //       active: false,
      //       path: '/dashboard/variant/create',
      //     },
      //   ],
      // },

      {
        title: 'Deals',
        icon: Gift,
        type: 'sub',
        active: false,
        path: paths.Deals,
        children: [
          {
            title: 'All Deals',
            icon: HardDrive,
            type: 'link',
            active: false,
            path: paths.Deals,
          },
          {
            title: 'Add Deals',
            icon: Plus,
            type: 'link',
            active: false,
            path: paths.AddDeal,
          },
        ],
      },
      {
        title: 'Roles',
        icon: Home,
        type: 'sub',
        active: true,
        path: '/dashboard/roles',
        children: [
          {
            title: 'All Roles',
            icon: HardDrive,
            type: 'link',
            active: false,
            path: '/dashboard/roles',
          },
          // ! not available
          // {
          //   title: 'Add Roles',
          //   icon: Plus,
          //   type: 'link',
          //   active: false,
          //   path: '/dashboard/role/create',
          // },
        ],
      },
      {
        title: 'Shops',
        icon: FaStore,
        type: 'sub',
        active: false,
        path: '/dashboard/shops',
        children: [
          {
            title: 'All Shops',
            icon: HardDrive,
            type: 'link',
            active: false,
            path: '/dashboard/shops',
          },
          {
            title: 'Add Shops',
            icon: Plus,
            type: 'link',
            active: false,
            path: '/dashboard/shop/create',
          },
        ],
      },
      {
        title: 'Banners',
        icon: FaImages,
        type: 'sub',
        active: false,
        children: [
          {
            title: 'All Banners',
            icon: HardDrive,
            type: 'link',
            active: false,
            path: '/banners/all',
          },
          {
            title: 'Add Banner',
            icon: Plus,
            type: 'link',
            active: false,
            path: '/banners/add',
          },
        ],
      },

      {
        title: 'Placeholders',
        icon: Package,
        type: 'sub',
        active: false,
        children: [
          {
            title: 'All PlaceHolders',
            icon: HardDrive,
            type: 'link',
            active: false,
            path: '/dashboard/placeholders',
          },
          {
            title: 'Add PlaceHolder',
            icon: Plus,
            type: 'link',
            active: false,
            path: '/dashboard/placeholder/create',
          },
        ],
      },

      {
        title: 'Site Nav',
        icon: Package,
        type: 'sub',
        active: false,
        children: [
          {
            title: 'All Site Nav',
            icon: HardDrive,
            type: 'link',
            active: false,
            path: '/dashboard/site-navs',
          },
          {
            title: 'Add Site Nav',
            icon: Plus,
            type: 'link',
            active: false,
            path: '/dashboard/site-nav/create',
          },
        ],
      },

      {
        title: 'Category',
        icon: HelpCircle,
        title: 'Manage Orders',
        icon: Truck,
        type: 'link',
        active: false,
        path: '/dashboard/orders',
      },

      {
        title: 'Vendors',
        icon: FaStoreAlt,
        type: 'sub',
        active: false,
        path: '/dashboard/vendors',
        children: [
          {
            title: 'All Vendors',
            icon: HardDrive,
            type: 'link',
            active: false,
            path: '/dashboard/vendors',
          },
          {
            title: 'Add Vendors',
            icon: Plus,
            type: 'link',
            active: false,
            path: '/dashboard/vendor/create',
          },
        ],
      },
      {
        title: 'Manage Coupons',
        icon: Paperclip,
        type: 'sub',
        active: false,
        path: '/dashboard/coupons',
        children: [
          {
            title: 'All Coupons',
            icon: HardDrive,
            type: 'link',
            active: false,
            path: '/dashboard/coupons',
          },
          {
            title: 'Add Coupons',
            icon: Plus,
            type: 'link',
            active: false,
            path: '/dashboard/coupon/create',
          },
        ],
      },

      // {
      //   title: 'Users',
      //   icon: FaUsers,
      //   type: 'sub',
      //   active: false,
      //   path: '/dashboard/user',
      //   children: [
      //     {
      //       title: 'All Users',
      //       icon: HardDrive,
      //       type: 'link',
      //       active: false,
      //       path: '/dashboard/users',
      //     },
      //     {
      //       title: 'Add User',
      //       icon: Plus,
      //       type: 'link',
      //       active: false,
      //       path: '/dashboard/user/create',
      //     },
      //   ],
      // },

      {
        title: 'Transactions',
        icon: DollarSign,
        type: 'link',
        active: false,
        path: '/dashboard/transactions/completed',
      },

      {
        title: ' App Config',
        icon: HelpCircle,
        type: 'sub',
        active: false,
        path: '/dashboard/setting',
        children: [
          {
            title: 'App setting ',
            icon: Plus,
            type: 'link',
            active: false,
            path: '/dashboard/app-setting',
          },

          {
            title: 'Pages ',
            icon: Plus,
            type: 'link',
            active: false,
            path: '/dashboard/pages',
          },
        ],
      },
      {
        title: 'Reviews',
        icon: Star,
        type: 'link',
        active: false,
        path: '/dashboard/reviews',
      },
      {
        title: 'Push Notification',
        icon: Bell,
        type: 'link',
        active: false,
        path: '/push-notification-templates',
      },
      {
        title: 'Email Template',
        icon: Mail,
        type: 'link',
        active: true,
        path: '/email-templates',
      },
      // {
      //   title: 'My Plans',
      //   icon: Award,
      //   type: 'link',
      //   active: false,
      //   path: '/dashboard/plans',
      // },
      // {
      //   title: 'Support',
      //   icon: HelpCircle,
      //   type: 'link',
      //   active: false,
      //   path: '/dashboard/support',
      // },
    ],
  },
];
