
const entities = '[placeholder]';

const action = {

  FETCH_PLACEHOLDER_GROUP_REQ: `${entities} FETCH_PLACEHOLDER_GROUP_REQ`,
  FETCH_PLACEHOLDER_GROUP_SUC: `${entities} FETCH_PLACEHOLDER_GROUP_SUC`,
  FETCH_PLACEHOLDER_GROUP_FAIL: `${entities} FETCH_PLACEHOLDER_GROUP_FAIL`,

  CREATE_PLACEHOLDER_GROUP_REQ: `${entities} CREATE_PLACEHOLDER_GROUP_REQ`,
  CREATE_PLACEHOLDER_GROUP_SUC: `${entities} CREATE_PLACEHOLDER_GROUP_SUC`,
  CREATE_PLACEHOLDER_GROUP_FAIL: `${entities} CREATE_PLACEHOLDER_GROUP_FAIL`,

  GET_SINGLE_PLACEHOLDER_GROUP_REQ: `${entities} GET_SINGLE_PLACEHOLDER_GROUP_REQ`,
  GET_SINGLE_PLACEHOLDER_GROUP_SUC: `${entities} GET_SINGLE_PLACEHOLDER_GROUP_SUC`,
  GET_SINGLE_PLACEHOLDER_GROUP_FAIL: `${entities} GET_SINGLE_PLACEHOLDER_GROUP_FAIL`,

  DELETE_PLACEHOLDER_GROUP_REQ: `${entities} DELETE_PLACEHOLDER_GROUP_REQ`,
  DELETE_PLACEHOLDER_GROUP_SUC: `${entities} DELETE_PLACEHOLDER_GROUP_SUC`,
  DELETE_PLACEHOLDER_GROUP_FAIL: `${entities} DELETE_PLACEHOLDER_GROUP_FAIL`,

  EDIT_PLACEHOLDER_GROUP_REQ: `${entities} EDIT_PLACEHOLDER_GROUP_REQ`,
  EDIT_PLACEHOLDER_GROUP_SUC: `${entities} EDIT_PLACEHOLDER_GROUP_SUC`,
  EDIT_PLACEHOLDER_GROUP_FAIL: `${entities} EDIT_PLACEHOLDER_GROUP_FAIL`,

  SEARCH_PLACEHOLDER_GROUP_REQ: `${entities} SEARCH_PLACEHOLDER_GROUP_REQ`,
  SEARCH_PLACEHOLDER_GROUP_SUC: `${entities} SEARCH_PLACEHOLDER_GROUP_SUC`,
  SEARCH_PLACEHOLDER_GROUP_FAIL: `${entities} SEARCH_PLACEHOLDER_GROUP_FAIL`,

  //Placeholder Items


  CREATE_PLACEHOLDER_ITEMS_REQ: `${entities} CREATE_PLACEHOLDER_ITEMS_REQ`,
  CREATE_PLACEHOLDER_ITEMS_SUC: `${entities} CREATE_PLACEHOLDER_ITEMS_SUC`,
  CREATE_PLACEHOLDER_ITEMS_FAIL: `${entities} CREATE_PLACEHOLDER_ITEMS_FAIL`,


  FETCH_CURRENT_PLACEHOLDER_ITEMS_REQ: `${entities} FETCH_CURRENT_PLACEHOLDER_ITEMS_REQ`,
  FETCH_CURRENT_PLACEHOLDER_ITEMS_SUC: `${entities} FETCH_CURRENT_PLACEHOLDER_ITEMS_SUC`,
  FETCH_CURRENT_PLACEHOLDER_ITEMS_FAIL: `${entities} FETCH_CURRENT_PLACEHOLDER_ITEMS_FAIL`,


  addPlaceholderReq: (payload) => ({
    type: action.CREATE_PLACEHOLDER_GROUP_REQ,
    payload,
  }),

  getPlaceholderReq: (payload) => ({
    type: action.FETCH_PLACEHOLDER_GROUP_REQ,
    payload,
  }),

  dltPlaceholderReq: (payload) => ({
    type: action.DELETE_PLACEHOLDER_GROUP_REQ,
    payload,
  }),

  updatePlaceholderReq: (id, data) => ({
    type: action.EDIT_PLACEHOLDER_GROUP_REQ,
    id,
    data
  }),

  searchPlaceholderReq: (data) => ({
    type: action.SEARCH_PLACEHOLDER_GROUP_REQ,
    data
  }),

  getSinglePlaceholder: (id) => ({
    type: action.GET_SINGLE_PLACEHOLDER_GROUP_REQ,
    id
  }),

  addPlaceholderItem: (data) => ({
    type: action.CREATE_PLACEHOLDER_ITEMS_REQ,
    data
  })


};

export default action;


