export const cities = [
  { value: 'Kathmandu', label: 'Kathmandu' },
  { value: 'Pokhara', label: 'Pokhara' },
  { value: 'Patan', label: 'Patan' },
  { value: 'Biratnagar', label: 'Biratnagar' },
  { value: 'Birganj', label: 'Birganj' },
  { value: 'Dharan', label: 'Dharan' },
  { value: 'Bharatpur', label: 'Bharatpur' },
  { value: 'Janakpur', label: 'Janakpur' },
  { value: 'Dhangadhi', label: 'Dhangadhi' },
  { value: 'Butwal', label: 'Butwal' },
  { value: 'Mahendranagar', label: 'Mahendranagar' },
  { value: 'Hetauda', label: 'Hetauda' },
  { value: 'Madhyapur Thimi', label: 'Madhyapur Thimi' },
  { value: 'Triyuga', label: 'Triyuga' },
  { value: 'Inaruwa', label: 'Inaruwa' },
  { value: 'Nepalgunj', label: 'Nepalgunj' },
  { value: 'Siddharthanagar', label: 'Siddharthanagar' },
  { value: 'Gulariya', label: 'Gulariya' },
  { value: 'Itahari', label: 'Itahari' },
  { value: 'Panauti', label: 'Panauti' },
  { value: 'Tikapur', label: 'Tikapur' },
  { value: 'Kirtipur', label: 'Kirtipur' },
  { value: 'Tulsipur', label: 'Tulsipur' },
  { value: 'Rajbiraj', label: 'Rajbiraj' },
  { value: 'Lahan', label: 'Lahan' },
  { value: 'Birendranagar', label: 'Birendranagar' },
  { value: 'Panauti', label: 'Panauti' },
  { value: 'Gaur', label: 'Gaur' },
  { value: 'Siraha', label: 'Siraha' },
  { value: 'Tansen', label: 'Tansen' },
  { value: 'Jaleshwar', label: 'Jaleshwar' },
  { value: 'Dipayal', label: 'Dipayal' },
  { value: 'Baglung', label: 'Baglung' },
  { value: 'Khadbari', label: 'Khadbari' },
  { value: 'Dhankuta', label: 'Dhankuta' },
  { value: 'Walin', label: 'Walin' },
  { value: 'Dailekh', label: 'Dailekh' },
  { value: 'Malangawa', label: 'Malangawa' },
  { value: 'Bhadrapur', label: 'Bhadrapur' },
  { value: 'Dadeldhura', label: 'Dadeldhura' },
  { value: 'Darchula', label: 'Darchula' },
  { value: 'Ilam', label: 'Ilam' },
  { value: 'Banepa', label: 'Banepa' },
  { value: 'Dhulikhel', label: 'Dhulikhel' },
  { value: 'Kankrabari Dovan', label: 'Kankrabari Dovan' },
  { value: 'Hari Bdr Tamang House', label: 'Hari Bdr Tamang House' },
  { value: 'Jumla', label: 'Jumla' },
  { value: 'Lobuche', label: 'Lobuche' },
  { value: 'Bhattarai Danda', label: 'Bhattarai Danda' },
  { value: 'Besisahar', label: 'Besisahar' },
  { value: 'Nagarkot', label: 'Nagarkot' },
  { value: 'Bhojpur', label: 'Bhojpur' },
  { value: 'Chitre', label: 'Chitre' },
  { value: 'Bhojpur', label: 'Bhojpur' },
  { value: 'Namche Bazar', label: 'Namche Bazar' },
  { value: 'Dihi', label: 'Dihi' },
  { value: 'Kodari', label: 'Kodari' },
];
